### ISSUE TITLE
 Unable to download report

### ISSUE THREAD

**Issue by dmitriim** [catalyst/moodle-local_sitenotice#71] opened 2024-05-08 00:27 UTC
when I click on the report download I get an error.

![image](https://github.com/catalyst/moodle-local_sitenotice/assets/4626431/fddeb7d1-bec9-4217-bc52-2cf6962f4730)

**Comment by TomoTsuyuki** [comment] 2024-06-18 06:15
This is duplicate of https://github.com/catalyst/moodle-local_sitenotice/issues/66

**Closed as completed by TomoTsuyuki** 2024-06-18 06:15 UTC
Labels: bug
